
package course.registration.systems;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

 //@author Naza Zuhair
 
public class Admin_Options extends javax.swing.JFrame {

    
    
    public Admin_Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        asminlogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnstudents = new javax.swing.JButton();
        btnprofile = new javax.swing.JButton();
        btncourses = new javax.swing.JButton();
        lblprofile = new javax.swing.JLabel();
        lblcourses = new javax.swing.JLabel();
        lblstudents = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlbody = new javax.swing.JPanel();
        pnlstudents = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        stdtable = new javax.swing.JTable();
        btnviewstds = new javax.swing.JButton();
        btnsearchstd = new javax.swing.JButton();
        search1 = new javax.swing.JTextField();
        pnlcourses = new javax.swing.JScrollPane();
        pnlcourses2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        courselvl = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        courseid = new javax.swing.JTextField();
        CourseName = new javax.swing.JTextField();
        coursedur = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblcourses = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btndelete1 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnviewcourses = new javax.swing.JButton();
        pnlprofile = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        admindetails = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        adminid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminadress = new javax.swing.JTextArea();
        adminname = new javax.swing.JTextField();
        adminemail = new javax.swing.JTextField();
        btnadminsave = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("adminoptions");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("adminoptions"); // NOI18N
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setForeground(new java.awt.Color(98, 98, 98));
        jLabel1.setText("You are logged in as Admin");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        asminlogout.setForeground(new java.awt.Color(51, 153, 255));
        asminlogout.setText("Logout?");
        asminlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asminlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asminlogoutMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(98, 98, 98));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course/registration/systems/Screenshot (2).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(98, 98, 98));
        jLabel4.setText("Naza Zuhair");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Administrator");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnstudents.setBackground(new java.awt.Color(255, 255, 255));
        btnstudents.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnstudents.setText("STUDENTS");
        btnstudents.setBorder(null);
        btnstudents.setContentAreaFilled(false);
        btnstudents.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnstudents.setFocusable(false);
        btnstudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentsActionPerformed(evt);
            }
        });

        btnprofile.setBackground(new java.awt.Color(255, 255, 255));
        btnprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnprofile.setText("MY PROFILE");
        btnprofile.setBorder(null);
        btnprofile.setBorderPainted(false);
        btnprofile.setContentAreaFilled(false);
        btnprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnprofile.setFocusable(false);
        btnprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofileActionPerformed(evt);
            }
        });

        btncourses.setBackground(new java.awt.Color(255, 255, 255));
        btncourses.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btncourses.setText("COURSES");
        btncourses.setBorder(null);
        btncourses.setContentAreaFilled(false);
        btncourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncourses.setFocusable(false);
        btncourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoursesActionPerformed(evt);
            }
        });

        lblprofile.setBackground(new java.awt.Color(64, 64, 159));
        lblprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblprofile.setOpaque(true);
        lblprofile.setPreferredSize(new java.awt.Dimension(125, 6));

        lblcourses.setBackground(new java.awt.Color(64, 64, 159));
        lblcourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblcourses.setOpaque(true);
        lblcourses.setPreferredSize(new java.awt.Dimension(120, 6));

        lblstudents.setBackground(new java.awt.Color(64, 64, 159));
        lblstudents.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblstudents.setOpaque(true);
        lblstudents.setPreferredSize(new java.awt.Dimension(120, 6));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("naza.zuhair@gmail.com");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asminlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(btncourses, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(121, 121, 121)
                                        .addComponent(btnstudents, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(lblcourses, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(lblstudents, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asminlogout)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnprofile)
                            .addComponent(btncourses)
                            .addComponent(btnstudents)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblstudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pnlbody.setBackground(new java.awt.Color(255, 255, 255));
        pnlbody.setLayout(new java.awt.CardLayout());

        pnlstudents.setBackground(new java.awt.Color(255, 255, 255));

        stdtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Degree level", "Email", "Contact No"
            }
        ));
        jScrollPane4.setViewportView(stdtable);

        btnviewstds.setBackground(new java.awt.Color(82, 82, 184));
        btnviewstds.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnviewstds.setForeground(new java.awt.Color(255, 255, 255));
        btnviewstds.setText("View Students");
        btnviewstds.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 3, true));
        btnviewstds.setContentAreaFilled(false);
        btnviewstds.setFocusable(false);
        btnviewstds.setOpaque(true);
        btnviewstds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnviewstdsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewstdsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewstdsMouseExited(evt);
            }
        });
        btnviewstds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewstdsActionPerformed(evt);
            }
        });

        btnsearchstd.setBackground(new java.awt.Color(82, 82, 184));
        btnsearchstd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsearchstd.setForeground(new java.awt.Color(255, 255, 255));
        btnsearchstd.setText("Search");
        btnsearchstd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 3, true));
        btnsearchstd.setContentAreaFilled(false);
        btnsearchstd.setFocusable(false);
        btnsearchstd.setOpaque(true);
        btnsearchstd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsearchstdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchstdMouseExited(evt);
            }
        });
        btnsearchstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchstdActionPerformed(evt);
            }
        });

        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlstudentsLayout = new javax.swing.GroupLayout(pnlstudents);
        pnlstudents.setLayout(pnlstudentsLayout);
        pnlstudentsLayout.setHorizontalGroup(
            pnlstudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlstudentsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlstudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlstudentsLayout.createSequentialGroup()
                        .addComponent(btnsearchstd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlstudentsLayout.createSequentialGroup()
                        .addComponent(btnviewstds, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pnlstudentsLayout.setVerticalGroup(
            pnlstudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlstudentsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlstudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchstd))
                .addGroup(pnlstudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlstudentsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlstudentsLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnviewstds)))
                .addGap(21, 21, 21))
        );

        pnlbody.add(pnlstudents, "card4");

        pnlcourses.setBackground(new java.awt.Color(255, 255, 255));
        pnlcourses.setBorder(null);
        pnlcourses.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlcourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlcourses.setInheritsPopupMenu(true);

        pnlcourses2.setBackground(new java.awt.Color(255, 255, 255));
        pnlcourses2.setPreferredSize(new java.awt.Dimension(1027, 600));
        pnlcourses2.setRequestFocusEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Course ID:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Course Name:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Course Level:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Course Duration:");

        courseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseidActionPerformed(evt);
            }
        });

        CourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseNameActionPerformed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(82, 82, 184));
        btnadd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add New Course");
        btnadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 229), 4));
        btnadd.setContentAreaFilled(false);
        btnadd.setFocusable(false);
        btnadd.setOpaque(true);
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaddMouseExited(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(82, 82, 184));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 4, true));
        btnupdate.setContentAreaFilled(false);
        btnupdate.setFocusable(false);
        btnupdate.setOpaque(true);
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupdateMouseExited(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(82, 82, 184));
        btndelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 4, true));
        btndelete.setContentAreaFilled(false);
        btndelete.setFocusable(false);
        btndelete.setOpaque(true);
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeleteMouseExited(evt);
            }
        });
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        tblcourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Level", "Duration in years"
            }
        ));
        tblcourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcoursesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblcourses);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("All Courses");

        btndelete1.setBackground(new java.awt.Color(82, 82, 184));
        btndelete1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btndelete1.setForeground(new java.awt.Color(255, 255, 255));
        btndelete1.setText("Search");
        btndelete1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 3, true));
        btndelete1.setContentAreaFilled(false);
        btndelete1.setFocusable(false);
        btndelete1.setOpaque(true);
        btndelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndelete1MouseExited(evt);
            }
        });
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(82, 82, 184));
        btnsave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 4, true));
        btnsave.setContentAreaFilled(false);
        btnsave.setFocusable(false);
        btnsave.setOpaque(true);
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsaveMouseExited(evt);
            }
        });
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnviewcourses.setBackground(new java.awt.Color(82, 82, 184));
        btnviewcourses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnviewcourses.setForeground(new java.awt.Color(255, 255, 255));
        btnviewcourses.setText("View Courses");
        btnviewcourses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 3, true));
        btnviewcourses.setContentAreaFilled(false);
        btnviewcourses.setFocusable(false);
        btnviewcourses.setOpaque(true);
        btnviewcourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnviewcoursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewcoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewcoursesMouseExited(evt);
            }
        });
        btnviewcourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewcoursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlcourses2Layout = new javax.swing.GroupLayout(pnlcourses2);
        pnlcourses2.setLayout(pnlcourses2Layout);
        pnlcourses2Layout.setHorizontalGroup(
            pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcourses2Layout.createSequentialGroup()
                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlcourses2Layout.createSequentialGroup()
                                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(courselvl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(coursedur, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcourses2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlcourses2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(courseid, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnviewcourses, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcourses2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addComponent(btndelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );
        pnlcourses2Layout.setVerticalGroup(
            pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcourses2Layout.createSequentialGroup()
                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcourses2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courselvl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coursedur, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndelete1)))
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlcourses2Layout.createSequentialGroup()
                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcourses2Layout.createSequentialGroup()
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnviewcourses))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlcourses.setViewportView(pnlcourses2);

        pnlbody.add(pnlcourses, "card2");

        pnlprofile.setBackground(new java.awt.Color(255, 255, 255));
        pnlprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Adress:");

        admindetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        admindetails.setForeground(new java.awt.Color(47, 47, 171));
        admindetails.setText("Manage Profile");
        admindetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admindetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admindetailsMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("Name:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Email Adress:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setText("Staff ID");

        adminid.setEditable(false);
        adminid.setBackground(new java.awt.Color(255, 255, 255));
        adminid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        adminid.setText("ST05673");
        adminid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(27, 27, 122)));
        adminid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminidActionPerformed(evt);
            }
        });

        adminadress.setEditable(false);
        adminadress.setColumns(20);
        adminadress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminadress.setRows(5);
        adminadress.setText("A-6-31, Savanna Condominium,\nJalan 1/155a, 57000, \nBUkit Jalil, Kuala Lumpur.");
        adminadress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 57, 121)));
        jScrollPane2.setViewportView(adminadress);

        adminname.setEditable(false);
        adminname.setBackground(new java.awt.Color(255, 255, 255));
        adminname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        adminname.setText("Naza Zuhair");
        adminname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(27, 27, 122)));
        adminname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminnameActionPerformed(evt);
            }
        });

        adminemail.setEditable(false);
        adminemail.setBackground(new java.awt.Color(255, 255, 255));
        adminemail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        adminemail.setText("naza.zuhair@gmail.com");
        adminemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(27, 27, 122)));
        adminemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminemailActionPerformed(evt);
            }
        });

        btnadminsave.setBackground(new java.awt.Color(82, 82, 184));
        btnadminsave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnadminsave.setForeground(new java.awt.Color(255, 255, 255));
        btnadminsave.setText("Save");
        btnadminsave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 4, true));
        btnadminsave.setContentAreaFilled(false);
        btnadminsave.setFocusable(false);
        btnadminsave.setOpaque(true);
        btnadminsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnadminsaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadminsaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadminsaveMouseExited(evt);
            }
        });
        btnadminsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlprofileLayout = new javax.swing.GroupLayout(pnlprofile);
        pnlprofile.setLayout(pnlprofileLayout);
        pnlprofileLayout.setHorizontalGroup(
            pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlprofileLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlprofileLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlprofileLayout.createSequentialGroup()
                        .addGroup(pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminemail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminid, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlprofileLayout.createSequentialGroup()
                        .addComponent(admindetails, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnadminsave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlprofileLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        pnlprofileLayout.setVerticalGroup(
            pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlprofileLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlprofileLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlprofileLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admindetails)
                    .addComponent(btnadminsave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pnlbody.add(pnlprofile, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlbody, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1054, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnstudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentsActionPerformed
        
        lblstudents.setBackground(new Color(64,64,159));
        
        lblcourses.setBackground(new Color(255,255,255));
        
        lblprofile.setBackground(new Color(255,255,255));
        
        pnlbody.removeAll();
        pnlbody.repaint();
        pnlbody.revalidate();
        pnlbody.add(pnlstudents);
        pnlbody.repaint();
        pnlbody.revalidate();
        
    }//GEN-LAST:event_btnstudentsActionPerformed

    private void btnprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofileActionPerformed
        
        lblprofile.setBackground(new Color(64,64,159));
        
        lblcourses.setBackground(new Color(255,255,255));
        
        lblstudents.setBackground(new Color(255,255,255));
        
        pnlbody.removeAll();
        pnlbody.repaint();
        pnlbody.revalidate();
        pnlbody.add(pnlprofile);
        pnlbody.repaint();
        pnlbody.revalidate();
        
    }//GEN-LAST:event_btnprofileActionPerformed

    private void btncoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoursesActionPerformed
        
        lblcourses.setBackground(new Color(64,64,159));
        
        lblprofile.setBackground(new Color(255,255,255));
        
        lblstudents.setBackground(new Color(255,255,255));
        
        pnlbody.removeAll();
        pnlbody.repaint();
        pnlbody.revalidate();
        pnlbody.add(pnlcourses);
        pnlbody.repaint();
        pnlbody.revalidate();
        
    }//GEN-LAST:event_btncoursesActionPerformed

    private void asminlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asminlogoutMouseClicked
        
        user userl = new user();
        userl.setVisible(true);
        userl.pack();
        userl.setLocationRelativeTo(null);
        userl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_asminlogoutMouseClicked

    private void CourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseNameActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        
        DefaultTableModel table = (DefaultTableModel)tblcourses.getModel();
        int i = tblcourses.getSelectedRow();
                
        if(i >= 0){
            table.setValueAt(courseid.getText(), i, 0);
            table.setValueAt(CourseName.getText(), i, 1);
            table.setValueAt(courselvl.getText(), i, 2);
            table.setValueAt(coursedur.getText(), i, 3);
        }
        else{
        System.out.println("Update Error");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        
        DefaultTableModel table = (DefaultTableModel)tblcourses.getModel();
                        // i = the index of the selected row
        int i = tblcourses.getSelectedRow();
        if(i >= 0){
                    // remove a row from jtable
            table.removeRow(i);
        }
        else{
            System.out.println("Delete Error");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void courseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseidActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

        
        DefaultTableModel table = (DefaultTableModel)tblcourses.getModel();
        Course c1;
        String n;
        // InputID = get input for Course ID from the textfields/user
        
        String cID =courseid.getText();
        String cname =CourseName.getText();
        String clevel =courselvl.getText();
        String cdur = coursedur.getText();
        c1 = new Course(cID, cname, clevel, cdur);
        
        table.addRow(new Object[] {cID, cname, clevel, cdur});
        
        
        /*
        Object[] columns ={"cID", "cname", "clevel", "cdur"};
        
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        
        // set the model to the table
        tblcourses.setModel(model);
        
        Object[] row = new Object[4];
        row[0] = courseid.getText();
        row[1] = CourseName.getText();
        row[2] = courselvl.getText();
        row[3] = coursedur.getText();
        model.addRow(row);
        */

    }//GEN-LAST:event_btnaddActionPerformed

    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndelete1ActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        
        DefaultTableModel table = (DefaultTableModel)tblcourses.getModel();
        String csearch = search.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tblcourses.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(csearch));
        
    }//GEN-LAST:event_searchKeyReleased

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        String filepath = "C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Courses.txt";
        String tempfile ="C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Temp.txt";
        File newfile = new File(tempfile);
        File oldfile = new File(filepath);
        String cId="";
        String cname= "";
        String clvl="";
        String cdur= "";
        try{
            FileWriter fw = new FileWriter(tempfile,true);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i < tblcourses.getRowCount(); i++){//rows
                for(int j = 0; j < tblcourses.getColumnCount(); j++){//columns
            bw.write(tblcourses.getValueAt(i, j).toString()+",");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
            oldfile.delete();
            File dump = new File(filepath);
            newfile.renameTo(dump);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Cannot Write");
        }
        
        
        
        //String filepath = "C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems";
        //File file = new File (filepath);
        /*
        try{
            
            FileWriter fw = new FileWriter("C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Courses.txt",true);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i < tblcourses.getRowCount(); i++){//rows
                for(int j = 0; j < tblcourses.getColumnCount(); j++){//columns
            bw.write(tblcourses.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        }
        catch(Exception e){
            
        }
        */
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnviewcoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewcoursesActionPerformed
        
        String filepath = "C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Courses.txt";
        File file = new File (filepath);
        try{
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel)tblcourses.getModel();
            model.setRowCount(0);
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(", ");
                model.addRow(row);
            }
            br.close();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_btnviewcoursesActionPerformed

    private void tblcoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcoursesMouseClicked
        
        DefaultTableModel table = (DefaultTableModel)tblcourses.getModel();
        int i = tblcourses.getSelectedRow();
            
        courseid.setText(table.getValueAt(i, 0).toString());
        CourseName.setText(table.getValueAt(i, 1).toString());
        courselvl.setText(table.getValueAt(i, 2).toString());
        coursedur.setText(table.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tblcoursesMouseClicked

    private void adminidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminidActionPerformed

    private void adminnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminnameActionPerformed

    private void adminemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminemailActionPerformed

    private void admindetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admindetailsMouseClicked
        
        adminname.setEditable(true);
        adminid.setEditable(true);
        adminemail.setEditable(true);
        adminadress.setEditable(true);
        btnadminsave.setVisible(true);
        admindetails.setVisible(false);
        
        
        
        
    }//GEN-LAST:event_admindetailsMouseClicked

    private void btnaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseEntered
        // TODO add your handling code here:
        btnadd.setBorderPainted(true);
        
        
    }//GEN-LAST:event_btnaddMouseEntered

    private void btnaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseExited
        // TODO add your handling code here:
        btnadd.setBorderPainted(false);
    }//GEN-LAST:event_btnaddMouseExited

    private void btnupdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseEntered
        // TODO add your handling code here:
        btnadd.setBorderPainted(true);
    }//GEN-LAST:event_btnupdateMouseEntered

    private void btnupdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseExited
        // TODO add your handling code here:
        btnadd.setBorderPainted(false);
    }//GEN-LAST:event_btnupdateMouseExited

    private void btndeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseEntered
        // TODO add your handling code here:
        btnadd.setBorderPainted(true);
    }//GEN-LAST:event_btndeleteMouseEntered

    private void btndeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseExited
        // TODO add your handling code here:
        btnadd.setBorderPainted(false);
    }//GEN-LAST:event_btndeleteMouseExited

    private void btnsaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseEntered
        // TODO add your handling code here:
        btnadd.setBorderPainted(true);
    }//GEN-LAST:event_btnsaveMouseEntered

    private void btnsaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseExited
        // TODO add your handling code here:
        btnadd.setBorderPainted(false);
    }//GEN-LAST:event_btnsaveMouseExited

    private void btndelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndelete1MouseEntered
        // TODO add your handling code here:
        btnadd.setBorderPainted(true);
    }//GEN-LAST:event_btndelete1MouseEntered

    private void btndelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndelete1MouseExited
        // TODO add your handling code here:
        btnadd.setBorderPainted(false);
    }//GEN-LAST:event_btndelete1MouseExited

    private void btnviewcoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewcoursesMouseEntered
        // TODO add your handling code here:
        btnadd.setBorderPainted(true);
    }//GEN-LAST:event_btnviewcoursesMouseEntered

    private void btnviewcoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewcoursesMouseExited
        // TODO add your handling code here:
        btnadd.setBorderPainted(true);
    }//GEN-LAST:event_btnviewcoursesMouseExited

    private void btnadminsaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadminsaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadminsaveMouseEntered

    private void btnadminsaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadminsaveMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadminsaveMouseExited

    private void btnadminsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadminsaveActionPerformed

    private void btnadminsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadminsaveMouseClicked
        // TODO add your handling code here:
        String filepath = "C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Admin.txt";
        String temp ="C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Temp.txt";
        File newfile = new File(temp);
        File oldfile = new File(filepath);
        
        String adname,adid,admail,adadress;
        //ADD A NEW COURSE
        //DEACLRE AN OBJECT OF THE COURSE
        
        
        //INITIALIZE THE OBJECT WITH CONSTRUCTORS
        
        adname = adminname.getText();
        adid=adminid.getText();
        admail=adminemail.getText();
        adadress =adminadress.getText();
        
        
        try{
            FileWriter ffw = new FileWriter(temp,true);
            BufferedWriter bbw = new BufferedWriter(ffw);
            bbw.write(adname+","+adid+","+admail+","+adadress);
            bbw.write("\r\n");
            
            
            bbw.close();
            ffw.close();
            oldfile.delete();
            File dumps = new File(filepath);
            newfile.renameTo(dumps);
            
            JOptionPane.showMessageDialog(this, "Admin Details Updated Successfully! ");
            adminname.setEditable(false);
            adminid.setEditable(false);
            adminemail.setEditable(false);
            adminadress.setEditable(false);
            btnadminsave.setVisible(false);
            admindetails.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
  
    }//GEN-LAST:event_btnadminsaveMouseClicked

    private void btnviewcoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewcoursesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewcoursesMouseClicked

    private void btnviewstdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewstdsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewstdsMouseClicked

    private void btnviewstdsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewstdsMouseEntered
        // TODO add your handling code here:
        btnviewstds.setBorderPainted(true);
    }//GEN-LAST:event_btnviewstdsMouseEntered

    private void btnviewstdsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewstdsMouseExited
        // TODO add your handling code here:
        btnviewstds.setBorderPainted(false);
    }//GEN-LAST:event_btnviewstdsMouseExited

    private void btnviewstdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewstdsActionPerformed

        String filepath = "C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Students.txt";
        File file = new File (filepath);
        try{

            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel)stdtable.getModel();
            model.setRowCount(0);
            Object[] lines = br.lines().toArray();

            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(",");
                model.addRow(row);
            }
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_btnviewstdsActionPerformed

    private void btnsearchstdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchstdMouseEntered
        // TODO add your handling code here:
        btnsearchstd.setBorderPainted(true);
    }//GEN-LAST:event_btnsearchstdMouseEntered

    private void btnsearchstdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchstdMouseExited
        // TODO add your handling code here:
        btnsearchstd.setBorderPainted(false);
    }//GEN-LAST:event_btnsearchstdMouseExited

    private void btnsearchstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchstdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchstdActionPerformed

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased

        DefaultTableModel table = (DefaultTableModel)stdtable.getModel();
        String csearch = search.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        stdtable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(csearch));
    }//GEN-LAST:event_search1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseName;
    private javax.swing.JTextArea adminadress;
    private javax.swing.JLabel admindetails;
    private javax.swing.JTextField adminemail;
    private javax.swing.JTextField adminid;
    private javax.swing.JTextField adminname;
    private javax.swing.JLabel asminlogout;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadminsave;
    private javax.swing.JButton btncourses;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btnprofile;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearchstd;
    private javax.swing.JButton btnstudents;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnviewcourses;
    private javax.swing.JButton btnviewstds;
    private javax.swing.JTextField coursedur;
    private javax.swing.JTextField courseid;
    private javax.swing.JTextField courselvl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcourses;
    private javax.swing.JLabel lblprofile;
    private javax.swing.JLabel lblstudents;
    private javax.swing.JPanel pnlbody;
    private javax.swing.JScrollPane pnlcourses;
    private javax.swing.JPanel pnlcourses2;
    private javax.swing.JPanel pnlprofile;
    private javax.swing.JPanel pnlstudents;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JTable stdtable;
    private javax.swing.JTable tblcourses;
    // End of variables declaration//GEN-END:variables
}
