/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course.registration.systems;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Naza Zuhair
 */
public class Student_options extends javax.swing.JFrame {

    /**
     * Creates new form Student_options
     */
    public Student_options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stdlogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnregister = new javax.swing.JButton();
        btnstdprofile = new javax.swing.JButton();
        btnstdcourses = new javax.swing.JButton();
        lblstdprofile = new javax.swing.JLabel();
        lblstdcourses = new javax.swing.JLabel();
        lblregister = new javax.swing.JLabel();
        pnlstdbody = new javax.swing.JPanel();
        pnlstdprofile = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        studentdetails = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        stnid = new javax.swing.JTextField();
        stnname = new javax.swing.JTextField();
        stnphno = new javax.swing.JTextField();
        btnstudentsave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        stnemail = new javax.swing.JTextField();
        stnlvl = new javax.swing.JTextField();
        pnlregister = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pnlstdcourses = new javax.swing.JScrollPane();
        pnlcourses2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblcoursess = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnsearchstd = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        btnregisters = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setForeground(new java.awt.Color(98, 98, 98));
        jLabel1.setText("You are logged in as Jamal");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stdlogout.setForeground(new java.awt.Color(51, 153, 255));
        stdlogout.setText("Logout?");
        stdlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stdlogoutMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(98, 98, 98));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course/registration/systems/peeple.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(98, 98, 98));
        jLabel4.setText("Jamal");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Student");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnregister.setBackground(new java.awt.Color(255, 255, 255));
        btnregister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnregister.setText("REGISTER");
        btnregister.setBorder(null);
        btnregister.setContentAreaFilled(false);
        btnregister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnregister.setFocusable(false);
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        btnstdprofile.setBackground(new java.awt.Color(255, 255, 255));
        btnstdprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnstdprofile.setText("MY PROFILE");
        btnstdprofile.setBorder(null);
        btnstdprofile.setBorderPainted(false);
        btnstdprofile.setContentAreaFilled(false);
        btnstdprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnstdprofile.setFocusable(false);
        btnstdprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstdprofileActionPerformed(evt);
            }
        });

        btnstdcourses.setBackground(new java.awt.Color(255, 255, 255));
        btnstdcourses.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnstdcourses.setText("MY COURSES");
        btnstdcourses.setBorder(null);
        btnstdcourses.setContentAreaFilled(false);
        btnstdcourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnstdcourses.setFocusable(false);
        btnstdcourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstdcoursesActionPerformed(evt);
            }
        });

        lblstdprofile.setBackground(new java.awt.Color(64, 64, 159));
        lblstdprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblstdprofile.setOpaque(true);
        lblstdprofile.setPreferredSize(new java.awt.Dimension(125, 6));

        lblstdcourses.setBackground(new java.awt.Color(64, 64, 159));
        lblstdcourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblstdcourses.setOpaque(true);
        lblstdcourses.setPreferredSize(new java.awt.Dimension(120, 6));

        lblregister.setBackground(new java.awt.Color(64, 64, 159));
        lblregister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblregister.setOpaque(true);
        lblregister.setPreferredSize(new java.awt.Dimension(120, 6));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stdlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnstdprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblstdprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblstdcourses, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(btnstdcourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblregister, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(btnregister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 79, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdlogout)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstdprofile)
                    .addComponent(btnstdcourses)
                    .addComponent(btnregister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblregister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblstdcourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblstdprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pnlstdbody.setBackground(new java.awt.Color(255, 255, 255));
        pnlstdbody.setLayout(new java.awt.CardLayout());

        pnlstdprofile.setBackground(new java.awt.Color(255, 255, 255));
        pnlstdprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Email ID:");

        studentdetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studentdetails.setForeground(new java.awt.Color(47, 47, 171));
        studentdetails.setText("Manage Profile");
        studentdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentdetailsMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("Name:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Degree Level:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setText("Student ID:");

        stnid.setEditable(false);
        stnid.setBackground(new java.awt.Color(255, 255, 255));
        stnid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        stnid.setText("TP05673");
        stnid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(27, 27, 122)));
        stnid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnidActionPerformed(evt);
            }
        });

        stnname.setEditable(false);
        stnname.setBackground(new java.awt.Color(255, 255, 255));
        stnname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        stnname.setText("Naza Zuhair");
        stnname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(27, 27, 122)));
        stnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnnameActionPerformed(evt);
            }
        });

        stnphno.setEditable(false);
        stnphno.setBackground(new java.awt.Color(255, 255, 255));
        stnphno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        stnphno.setText("+6017647404");
        stnphno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(27, 27, 122)));
        stnphno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnphnoActionPerformed(evt);
            }
        });

        btnstudentsave.setBackground(new java.awt.Color(82, 82, 184));
        btnstudentsave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnstudentsave.setForeground(new java.awt.Color(255, 255, 255));
        btnstudentsave.setText("Save");
        btnstudentsave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 4, true));
        btnstudentsave.setContentAreaFilled(false);
        btnstudentsave.setFocusable(false);
        btnstudentsave.setOpaque(true);
        btnstudentsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnstudentsaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnstudentsaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnstudentsaveMouseExited(evt);
            }
        });
        btnstudentsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentsaveActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Contact No:");

        stnemail.setEditable(false);
        stnemail.setBackground(new java.awt.Color(255, 255, 255));
        stnemail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        stnemail.setText("naza.zuhair@gmail.com");
        stnemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(27, 27, 122)));
        stnemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnemailActionPerformed(evt);
            }
        });

        stnlvl.setEditable(false);
        stnlvl.setBackground(new java.awt.Color(255, 255, 255));
        stnlvl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        stnlvl.setText("2");
        stnlvl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(27, 27, 122)));
        stnlvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnlvlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlstdprofileLayout = new javax.swing.GroupLayout(pnlstdprofile);
        pnlstdprofile.setLayout(pnlstdprofileLayout);
        pnlstdprofileLayout.setHorizontalGroup(
            pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlstdprofileLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlstdprofileLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stnname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlstdprofileLayout.createSequentialGroup()
                        .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stnphno, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stnid, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stnemail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stnlvl, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlstdprofileLayout.createSequentialGroup()
                        .addComponent(studentdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnstudentsave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(681, Short.MAX_VALUE))
        );
        pnlstdprofileLayout.setVerticalGroup(
            pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlstdprofileLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stnname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stnid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stnlvl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stnemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stnphno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlstdprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentdetails)
                    .addComponent(btnstudentsave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pnlstdbody.add(pnlstdprofile, "card3");

        pnlregister.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout pnlregisterLayout = new javax.swing.GroupLayout(pnlregister);
        pnlregister.setLayout(pnlregisterLayout);
        pnlregisterLayout.setHorizontalGroup(
            pnlregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlregisterLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        pnlregisterLayout.setVerticalGroup(
            pnlregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlregisterLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pnlstdbody.add(pnlregister, "card4");

        pnlstdcourses.setBackground(new java.awt.Color(255, 255, 255));
        pnlstdcourses.setBorder(null);
        pnlstdcourses.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlstdcourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlstdcourses.setInheritsPopupMenu(true);

        pnlcourses2.setBackground(new java.awt.Color(255, 255, 255));
        pnlcourses2.setPreferredSize(new java.awt.Dimension(1027, 600));
        pnlcourses2.setRequestFocusEnabled(false);

        tblcoursess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Level", "Duration"
            }
        ));
        tblcoursess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcoursessMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblcoursess);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("My Courses");

        btnsearchstd.setBackground(new java.awt.Color(82, 82, 184));
        btnsearchstd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsearchstd.setForeground(new java.awt.Color(255, 255, 255));
        btnsearchstd.setText("Search");
        btnsearchstd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 3, true));
        btnsearchstd.setContentAreaFilled(false);
        btnsearchstd.setFocusable(false);
        btnsearchstd.setOpaque(true);
        btnsearchstd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsearchstdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchstdMouseExited(evt);
            }
        });
        btnsearchstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchstdActionPerformed(evt);
            }
        });

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        btnregisters.setBackground(new java.awt.Color(82, 82, 184));
        btnregisters.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnregisters.setForeground(new java.awt.Color(255, 255, 255));
        btnregisters.setText("Register");
        btnregisters.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 229), 3, true));
        btnregisters.setContentAreaFilled(false);
        btnregisters.setFocusable(false);
        btnregisters.setOpaque(true);
        btnregisters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnregistersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregistersMouseExited(evt);
            }
        });
        btnregisters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlcourses2Layout = new javax.swing.GroupLayout(pnlcourses2);
        pnlcourses2.setLayout(pnlcourses2Layout);
        pnlcourses2Layout.setHorizontalGroup(
            pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcourses2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsearchstd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(pnlcourses2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcourses2Layout.createSequentialGroup()
                        .addComponent(btnregisters, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))))
        );
        pnlcourses2Layout.setVerticalGroup(
            pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcourses2Layout.createSequentialGroup()
                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlcourses2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnregisters)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlcourses2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearchstd)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pnlstdcourses.setViewportView(pnlcourses2);

        pnlstdbody.add(pnlstdcourses, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlstdbody, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlstdbody, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdlogoutMouseClicked
        
        Student_Login stndlgn = new Student_Login();
        stndlgn.setVisible(true);
        stndlgn.pack();
        stndlgn.setLocationRelativeTo(null);
        stndlgn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_stdlogoutMouseClicked

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed

        lblregister.setBackground(new Color(64,64,159));

        lblstdcourses.setBackground(new Color(255,255,255));

        lblstdprofile.setBackground(new Color(255,255,255));

        pnlstdbody.removeAll();
        pnlstdbody.repaint();
        pnlstdbody.revalidate();
        pnlstdbody.add(pnlregister);
        pnlstdbody.repaint();
        pnlstdbody.revalidate();

    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnstdprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstdprofileActionPerformed

        lblstdprofile.setBackground(new Color(64,64,159));

        lblstdcourses.setBackground(new Color(255,255,255));

        lblregister.setBackground(new Color(255,255,255));

        pnlstdbody.removeAll();
        pnlstdbody.repaint();
        pnlstdbody.revalidate();
        pnlstdbody.add(pnlstdprofile);
        pnlstdbody.repaint();
        pnlstdbody.revalidate();

    }//GEN-LAST:event_btnstdprofileActionPerformed

    private void btnstdcoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstdcoursesActionPerformed

        lblstdcourses.setBackground(new Color(64,64,159));

        lblstdprofile.setBackground(new Color(255,255,255));

        lblregister.setBackground(new Color(255,255,255));

        pnlstdbody.removeAll();
        pnlstdbody.repaint();
        pnlstdbody.revalidate();
        pnlstdbody.add(pnlstdcourses);
        pnlstdbody.repaint();
        pnlstdbody.revalidate();

    }//GEN-LAST:event_btnstdcoursesActionPerformed

    private void studentdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentdetailsMouseClicked

        stnname.setEditable(true);
        stnid.setEditable(false);
        stnphno.setEditable(true);
        stnemail.setEditable(true);
        stnlvl.setEditable(true);
        btnstudentsave.setVisible(true);
        studentdetails.setVisible(false);

    }//GEN-LAST:event_studentdetailsMouseClicked

    private void stnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stnidActionPerformed

    private void stnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stnnameActionPerformed

    private void stnphnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnphnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stnphnoActionPerformed

    private void btnstudentsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstudentsaveMouseClicked
        // TODO add your handling code here:
        String filpath = "C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Student.txt";
        String tempt ="C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Tempt.txt";
        File nwfile = new File(tempt);
        File odfile = new File(filpath);

        String studentname, studentid, studentemail, studentlevel, studentno;

        studentname = stnname.getText();
        studentid=stnid.getText();
        studentno= stnphno.getText();
        studentemail =stnemail.getText();
        studentlevel = stnlvl.getText();
        

        try{
            FileWriter fwr = new FileWriter(tempt,true);
            BufferedWriter bwr = new BufferedWriter(fwr);
            bwr.write(studentname+","+studentid+","+studentlevel+","+studentemail+","+studentno);
            bwr.write("\r\n");

            bwr.close();
            fwr.close();
            odfile.delete();
            File dups = new File(filpath);
            nwfile.renameTo(dups);

            JOptionPane.showMessageDialog(this, "Student Details Updated Successfully! ");
            stnname.setEditable(false);
            stnid.setEditable(false);
            stnphno.setEditable(false);
            stnlvl.setEditable(false);
            stnemail.setEditable(false);
            btnstudentsave.setVisible(false);
            studentdetails.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }

    }//GEN-LAST:event_btnstudentsaveMouseClicked

    private void btnstudentsaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstudentsaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstudentsaveMouseEntered

    private void btnstudentsaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstudentsaveMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstudentsaveMouseExited

    private void btnstudentsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstudentsaveActionPerformed

    private void tblcoursessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcoursessMouseClicked
         
      
    }//GEN-LAST:event_tblcoursessMouseClicked

    private void btnsearchstdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchstdMouseEntered
        // TODO add your handling code here:
        btnsearchstd.setBorderPainted(true);
    }//GEN-LAST:event_btnsearchstdMouseEntered

    private void btnsearchstdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchstdMouseExited
        // TODO add your handling code here:
        btnsearchstd.setBorderPainted(false);
    }//GEN-LAST:event_btnsearchstdMouseExited

    private void btnsearchstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchstdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchstdActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased

        DefaultTableModel table = (DefaultTableModel)tblcoursess.getModel();
        String csearch = search.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tblcoursess.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(csearch));

    }//GEN-LAST:event_searchKeyReleased

    private void stnemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stnemailActionPerformed

    private void stnlvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnlvlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stnlvlActionPerformed

    private void btnregistersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistersMouseClicked

    private void btnregistersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistersMouseEntered
        // TODO add your handling code here:
        btnregisters.setBorderPainted(true);
    }//GEN-LAST:event_btnregistersMouseEntered

    private void btnregistersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistersMouseExited
        // TODO add your handling code here:
        btnregisters.setBorderPainted(false);
    }//GEN-LAST:event_btnregistersMouseExited

    private void btnregistersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistersActionPerformed

        String filepath = "C:/Users/Naza Zuhair/Documents/NetBeansProjects/Course Registration Systems/Courses.txt";
        File file = new File (filepath);
        try{

            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel)tblcoursess.getModel();
            model.setRowCount(0);
            Object[] lines = br.lines().toArray();

            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_btnregistersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnregisters;
    private javax.swing.JButton btnsearchstd;
    private javax.swing.JButton btnstdcourses;
    private javax.swing.JButton btnstdprofile;
    private javax.swing.JButton btnstudentsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblregister;
    private javax.swing.JLabel lblstdcourses;
    private javax.swing.JLabel lblstdprofile;
    private javax.swing.JPanel pnlcourses2;
    private javax.swing.JPanel pnlregister;
    private javax.swing.JPanel pnlstdbody;
    private javax.swing.JScrollPane pnlstdcourses;
    private javax.swing.JPanel pnlstdprofile;
    private javax.swing.JTextField search;
    private javax.swing.JLabel stdlogout;
    private javax.swing.JTextField stnemail;
    private javax.swing.JTextField stnid;
    private javax.swing.JTextField stnlvl;
    private javax.swing.JTextField stnname;
    private javax.swing.JTextField stnphno;
    private javax.swing.JLabel studentdetails;
    private javax.swing.JTable tblcoursess;
    // End of variables declaration//GEN-END:variables
}
