/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course.registration.systems;

import javax.swing.JFrame;

/**
 *
 * @author Naza Zuhair
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnstudent = new javax.swing.JButton();
        btnnewuser1 = new javax.swing.JButton();
        btnadmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 47, 152));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Registration System");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnstudent.setBackground(new java.awt.Color(255, 204, 255));
        btnstudent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnstudent.setForeground(new java.awt.Color(255, 255, 255));
        btnstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course/registration/systems/icons8-contacts-32 (3).png"))); // NOI18N
        btnstudent.setText("Student");
        btnstudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 229), 4));
        btnstudent.setContentAreaFilled(false);
        btnstudent.setFocusable(false);
        btnstudent.setOpaque(true);
        btnstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnstudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnstudentMouseExited(evt);
            }
        });
        btnstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentActionPerformed(evt);
            }
        });

        btnnewuser1.setBackground(new java.awt.Color(255, 204, 255));
        btnnewuser1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnnewuser1.setForeground(new java.awt.Color(255, 255, 255));
        btnnewuser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course/registration/systems/icons8-add-32.png"))); // NOI18N
        btnnewuser1.setText("New User");
        btnnewuser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 229), 4));
        btnnewuser1.setContentAreaFilled(false);
        btnnewuser1.setFocusable(false);
        btnnewuser1.setOpaque(true);
        btnnewuser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnnewuser1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnewuser1MouseExited(evt);
            }
        });
        btnnewuser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewuser1ActionPerformed(evt);
            }
        });

        btnadmin.setBackground(new java.awt.Color(255, 204, 255));
        btnadmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course/registration/systems/icons8-businessman-24.png"))); // NOI18N
        btnadmin.setText("Admin");
        btnadmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 229), 4));
        btnadmin.setContentAreaFilled(false);
        btnadmin.setFocusable(false);
        btnadmin.setOpaque(true);
        btnadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadminMouseExited(evt);
            }
        });
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(70, Short.MAX_VALUE)
                    .addComponent(btnnewuser1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(399, Short.MAX_VALUE)
                    .addComponent(btnnewuser1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstudentMouseEntered
        
        btnstudent.setBorderPainted(true);
        
    }//GEN-LAST:event_btnstudentMouseEntered

    private void btnstudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstudentMouseExited
        
        btnstudent.setBorderPainted(false);
        
    }//GEN-LAST:event_btnstudentMouseExited

    private void btnstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentActionPerformed

        Student_Login stnlogin = new Student_Login();
        stnlogin.setVisible(true);
        stnlogin.pack();
        stnlogin.setLocationRelativeTo(null);
        stnlogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        /*
        Object[] columns ={"cID", "cname", "clevel", "cdur"};

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);

        // set the model to the table
        tblcourses.setModel(model);

        Object[] row = new Object[4];
        row[0] = courseid.getText();
        row[1] = CourseName.getText();
        row[2] = courselvl.getText();
        row[3] = coursedur.getText();
        model.addRow(row);
        */
    }//GEN-LAST:event_btnstudentActionPerformed

    private void btnnewuser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewuser1MouseEntered
        btnstudent.setBorderPainted(true);
    }//GEN-LAST:event_btnnewuser1MouseEntered

    private void btnnewuser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewuser1MouseExited
        btnstudent.setBorderPainted(false);
    }//GEN-LAST:event_btnnewuser1MouseExited

    private void btnnewuser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewuser1ActionPerformed
        
        Student_Register stdregister = new Student_Register();
        stdregister.setVisible(true);
        stdregister.pack();
        stdregister.setLocationRelativeTo(null);
        stdregister.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_btnnewuser1ActionPerformed

    private void btnadminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadminMouseEntered
        btnstudent.setBorderPainted(true);
    }//GEN-LAST:event_btnadminMouseEntered

    private void btnadminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadminMouseExited
        btnstudent.setBorderPainted(false);
    }//GEN-LAST:event_btnadminMouseExited

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
        
        Admin_Login adminlogin = new Admin_Login();
        adminlogin.setVisible(true);
        adminlogin.pack();
        adminlogin.setLocationRelativeTo(null);
        adminlogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_btnadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btnnewuser1;
    private javax.swing.JButton btnstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
